project:
  type: website


website:
  title: "Nasdaq Explorer"
  twitter-card: true
  open-graph: true
  navbar:
    
    left:
      - href: index.qmd
        text: Home
      
      - href: experience.qmd
        text: Experience and Skills
      - text: Projects
        menu: 
          - text: "Business Intelligence and Data Analytics"
            href: projects_bi.qmd
          - text: "Machine Learning and Deep Learning"
            href: projects_ml.qmd

      - href: blogs.qmd
        text: Blogs 

