project:
  type: website


website:
  title: "Nasdaq Explorer"
  twitter-card: true
  open-graph: true
  navbar:
    
    left:
      - href: index.qmd
        text: Home

      - text: Forecasting Models 
        menu: 
          - text: "Business Intelligence and Data Analytics"
            href: projects_bi.qmd
          - text: "Machine Learning and Deep Learning"
            href: projects_ml.qmd

  page-footer: 
    left: "Created by Sherwin Varghese" 
    right: 
      - icon: github
        href: https://github.com/Sherwin-14
        target: _blank

      - icon: linkedin
        href: https://linkedin.com/in/sherwin14/
        target: _blank

      - icon: medium
        href: https://medium.com/@varghesesherwin   
        target: _blank

    border: True


format:
  html:
    theme: darkly
    css: styles.css
