project:
  type: website


website:
  title: "Nasdaq Explorer"
  twitter-card: true
  open-graph: true
  navbar:
    
    left:
      - href: index.qmd
        text: Home

      - text: Forecasting Models 
        menu: 
          - text: "ARIMA"
            href: sections/arima.qmd
          - text: "FB Prophet"
            href: sections/fb_prophet.qmd
          - text: "SARIMA"
            href: sections/sarima.qmd
          - text: "Machine Learning"
            href: sections/ml_models.qmd
          - text: "Deep Learning"
            href: sections/dl_models.qmd

  page-footer: 
    left: "Created by Sherwin Varghese" 
    right: 
      - icon: github
        href: https://github.com/Sherwin-14
        target: _blank

      - icon: linkedin
        href: https://linkedin.com/in/sherwin14/
        target: _blank

      - icon: medium
        href: https://medium.com/@varghesesherwin   
        target: _blank

    border: True

format:
  html:
    theme: darkly
    css: styles.css
