# Machine Learning Models

Our stock prediction tool has a section for machine learning techniques to analyze and forecast time series data. Currently, we only support  XGBoost but we are planning to add more algorithms in the upcoming versions. 

## XGBoost Model Overview

Our XGBoost model is a powerful and is well-suited for handling complex time series data. The model is trained on a combination of technical indicators and moving averages, including:

☞ Simple Moving Averages (SMA): 5, 10, 15, 30

☞ Exponential Moving Average (EMA): 9

☞ Relative Strength Index (RSI): 14

☞ Moving Average Convergence Divergence (MACD): 12, 26

These features are used to capture trends, momentum, and volatility in the time series data. The XGBoost model is trained to predict future values based on these features.

## Training and Forecasting using ML Models

1. Load the stationarized dataset.

2. Choose the algorithm from the select bar and click on the Start Forecasting button to train the data using the selected algorithm.

3. After training rmse and best model parameters would be displayed.

4. A graph will be generated showing the history of the training dataset, the test dataset, and the performance of the model on test dataset.

5. A feature importance graph would also be generated at the end.



