# Deep Learning Models

Our stock prediction tool has a section for deep learning techniques to analyze and forecast time series data. Currently, we only support LSTM but we are planning to add more algorithms in the upcoming versions. 

## LSTM Model Overview

Our LSTM model is powerful and  well-suited for handling complex time series data. Also it gives out the next 7 day forecast just like ARIMA and SARIMA models do. The data is internally scaled and transformed and then model is built with the ideal set of parameters.

## Training and Forecasting using DL Models

1. Load the stationarized dataset.

2. Choose the algorithm from the select bar and click on the Start Forecasting button to train the data using the selected algorithm.

3. After training rmse and best model parameters would be displayed.

4. A graph will be generated showing the history of the stock and the predictions for the next 7 days.

5. Below the graph you will se the next 7 day forecast printed in metric format.